/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package exercice

import io.kotest.core.spec.style.FreeSpec
import io.kotest.matchers.shouldBe

class AppSpec : FreeSpec({
    "Example 1" {
        computeCost(3, intArrayOf(2, 2, 3)) shouldBe intArrayOf(0, 1, 2)
    }

    "Example 2" {
        computeCost(5, intArrayOf(1, 2, 3, 4, 5)) shouldBe intArrayOf(0, 1, 2, 3, 4)
    }

    "Example 3" {
        computeCost(7, intArrayOf(4, 4, 4, 4, 7, 7, 7)) shouldBe intArrayOf(0, 1, 2, 1, 2, 3, 3)
    }
})
