/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package exercice

fun main() {
    val n = readLine()!!.toInt()
    val shortcuts = readLine()!!.split(' ').map { it.toInt() }
    val costs = computeCost(n, shortcuts.toIntArray())
    println(costs.joinToString(" "))
}

fun computeCost(n: Int, shortcuts: IntArray): IntArray {
    val earliestShortcut: Map<Int, Int> = mutableMapOf<Int, Int>().apply {
        shortcuts.forEachIndexed { origin, target ->
            // target is 1-indexed
            if (origin < target - 1) { // if shortcut doesn't link to itself
                putIfAbsent(target - 1, origin)
            }
        }
    }
    val costs = IntArray(n)
    costs[0] = 0 // origin
    for (i in 1 until n) {
        // Either there was a shortcut to current node, or we're coming from the previous one.
        costs[i] = costs[earliestShortcut.getOrDefault(i, i - 1)] + 1
    }

    return costs
}
